### ISSUE TITLE
I'm testing your experience

### ISSUE THREAD

**Issue by Baio1977** [perez987/6600XT-on-macOS-with-PowerPlayTable-to-SSDT-or-config.plist#1] opened 2022-10-19 19:52 UTC
https://github.com/Baio1977/GA-Z490M-Gaming-X this is my reposity.

Section AMD 5000 and 6000 in Monterey 12.3 :
When I go to set the graphics properties for the graphics performance they collapse
![photo_2022-10-19_21-38-58](https://user-images.githubusercontent.com/59058746/196787696-e47777ac-d705-41c7-9b99-0e0cf0f40fff.jpg)
These are the performances starting normally
![photo_2022-10-19_21-41-37](https://user-images.githubusercontent.com/59058746/196788225-5b993461-24dc-4ced-9452-5783b26d3898.jpg)

do you encounter this problem ??

EDIT:
I have disabled IGPU from Bios, as the real Mac 20.1 

As a result, I have now gained in the Bench
![Screenshot 2022-10-19 alle 22 17 44](https://user-images.githubusercontent.com/59058746/196796678-e744e4d0-b2f1-4487-b8c2-0b991de33d7a.png)

**Comment by perez987** [comment] 2022-10-20 08:19
Good morning @Baio1977 

I have seen in my hack (as commented in the README):

- SMBIOSes lacking iGPU (MacPro and iMacPro) run better with zero code for iGPU in config. plist. Headless mode gets better results than the long code for carrying the display but no code gets the best results. 
- SMBIOSes lacking iGPU must work with iGPU disabled in BIOS or with -wegswitchgpu boot arg, so they use only dGPU. And of course no code for iGPU in config.plist.
- SMBIOS iMac19,x or 20,x are supposed to have iGPU so they work fine with iGPU code for headless mode, the short code, and iGPU enabled in BIOS.
- SMBIOSes lacking iGPU need framebuffer patch or sPPT to run on Ventura, not on Monterey. When having one of these settings (patch or sPPT) GB 5 scores drop down significantly. As a side effect, Zero RPM is disabled and fans are spinning all the time.

**Comment by Baio1977** [comment] 2022-10-20 16:19
Test 1 : 
I insert ATY,Henbury in SSDT, SMBios Imac20.1 + IGPU AAPL,ig-platform-id 0300C89B.
Score:
![Screenshot 2022-10-20 alle 18 17 30](https://user-images.githubusercontent.com/59058746/197003468-0242734d-6ccb-4212-aee0-018c30136cac.png)

Test 2:
SMBios Imac 20.1 + IGPU AAPL, ig-platform-id 0300C89B.
Score:
![Screenshot 2022-10-20 alle 18 21 25](https://user-images.githubusercontent.com/59058746/197004301-e3bacab3-15ed-4d41-9f97-e6b4acb535f4.png)

I noticed when I use in config.plist device properties for the RX 6600XT.
![Screenshot 2022-10-20 alle 18 23 49](https://user-images.githubusercontent.com/59058746/197004773-b9d8c2e8-da4a-4bdc-a7b7-0344f0d20729.png)

AAPL,slot-name Internal@0,1,0/0,0/0,0/0,0 I don't like this.
![Screenshot 2022-10-20 alle 18 25 38](https://user-images.githubusercontent.com/59058746/197005166-b7bf6e7d-ed3d-4fed-9deb-cffe77349838.png)

When I remove the device properties, the description of the BigNavi appears as it should be.
![Screenshot 2022-10-20 alle 18 28 57](https://user-images.githubusercontent.com/59058746/197005823-61a999c9-7bee-45dd-a6c4-f55f80e07935.png)

**Comment by perez987** [comment] 2022-10-20 19:44
@Baio1977 
We are coincident. Adding _Henbury_ patch drops significantly the GB 5 scores. Without it, scores are as expected. But the users wanting to have MacPro or iMacPro on Ventura must have it. Not needed with iMac SMBIOS. So really you don't need it since you are using iMac20,1.

About DeviceProperties: I don't have any code for the RX 6600 in config.plist, of course not the slot-name, it's better to leave macOS to set this automatically. This is my screenshot, Ventura RC, I don't know why I have Slot `J6B1` and you have `Internal@0,1,0`, it must be related to the different motherboards.

<img width="410" alt="rx6600" src="https://user-images.githubusercontent.com/50429399/197042889-eb0108e9-e659-474f-8642-691a3f844be7.png">

**Comment by Baio1977** [comment] 2022-10-20 19:55
Do you have SSDT Navi ??? in case the string in SSDT is the problem.

"Name (_SUN, One)  // _SUN: Slot User Number"

![Screenshot 2022-10-20 alle 21 56 56](https://user-images.githubusercontent.com/59058746/197045626-175235f7-0867-42c5-960e-5435b3087f8a.png)

**Comment by perez987** [comment] 2022-10-21 07:10
@Baio1977 
Ah! Yes, I have SSDT-NAVI, I’ll try without it and comment. But seeing your last pic, it is as you say.

**Comment by perez987** [comment] 2022-10-21 09:29
@Baio1977 
Without SSDT-NAVI the slot item disappears from System Profiler.
<img width="298" alt="ssdt-navi-no" src="https://user-images.githubusercontent.com/50429399/197162620-be0ef791-217b-4c0a-92ef-0aadc570248f.png">

Because the RX 6600 now is seen as integrated, not know why, it is confirmed checking the GPU tab in Activity Monitor.
<img width="241" alt="gpu-tab" src="https://user-images.githubusercontent.com/50429399/197162933-4b002c63-1011-452b-8e8f-f975112f5b0a.png">

Scores are the same with or without SSDT-NAVI, I have this SSDT for a while but really I can't remember why I added it, maybe when I was looking for a way to enable DisplayPort audio from the monitor.
Smetterò di usarlo.

**Comment by Baio1977** [comment] 2022-10-21 16:52
I have questions about how this GPU works.
I had an RX590 before and switched to RX 6600XT I encountered some problems.

1 - when I come home and wake up the PC I have a black screen, I have to disconnect the HDMI cable and reconnect it to see the desk.

2 - the boot is much longer, after the verbose I have to wait 7-10 seconds to display the screen where to enter the password.

On windows it works fine and the times are the same as I had with RX 590, so the problem is only in Hackintosh.

Your experience ??

**Comment by perez987** [comment] 2022-10-21 17:10
No, I don’t have such issue. PC wakes from keyboard, mouse or power button, a couple of seconds and screen is on. I’m using DisplayPort but tried HDMI and also wakes fine. 
Please let me see your config.plist or EFI. 

About the second question. Total boot time with RX 6600 (or RX 6600 XT on the other hack) seems to be similar to the one with my old RX 580. I boot without verbose, Apple logo and progress bar are displayed a few seconds, when progress bar is about 30% screen goes black for around 7-10", after that I see the desktop. Since OpenCore picker dissapears, I wait around 12-15" for the desktop. 
The black screen time, not seen on real Macs, happens while changing from default VESA graphics driver to accelerated driver. Maybe it’s a bit longer with 6600 than with 580, but I can’t be sure.

**Comment by Baio1977** [comment] 2022-10-21 18:15
OK so the startup and screen display times seem to me to confirm my experience.
As for the EFI it is the same EFI I had with RX 580 use SSDT-USBW + respective kext.
Previously with RX 580 it woke up in the same way it wakes up to you.

This ACPI and config.plist 
[Archivio.zip](https://github.com/perez987/RX6600XT-on-macOS-12-13-with-PowerPlayTable/files/9841456/Archivio.zip)

**Comment by perez987** [comment] 2022-10-21 18:39
@Baio1977 

I see you have all SSDT in a single file. I don't see anything strange in the config.plist. It's ok for me. I don't know why the screen doesn't wake well, you say that the only change is the graphics card but this is not enough to harm the sleep.

Do you need ResetLogoStatus?

Setting SetApfsTrimTimeout to 0 does enhance the boot time?

By the way, I discovered the Semplici icons pack in HackintoshLife a few days ago, the are very beautiful, I have them in the OC boot picker, I like them.

**Comment by Baio1977** [comment] 2022-10-21 22:12
I made a single SSDT contains aesthetic and functional patches that make it very similar to the acpi of a real mac itself SMBios.
I am sure of perfect functioning because tested with RX 590 for many years.
It was perfect, so whatever it is is down to the new GPU.
For the theme I think it is pleasant and colorful, I like it.
SetApfsTrimTimeout to 0, never noticed any difference, but I'll test it these days.

**Comment by perez987** [comment] 2022-10-22 00:37
Ok, I hope you’ll fix the wake issue. Closing this. You can follow posting despite its closed state. Ciao.

**Comment by Baio1977** [comment] 2022-10-31 12:00
I brought my Geekbench 82K Navi to 98K by adding parts in device properties that I found inside the kext FB_Navi.

![Screenshot 2022-10-30 alle 09 01 50](https://user-images.githubusercontent.com/59058746/199002974-0813573c-ce89-4f75-86da-50e8eabe7f7d.png)

![Screenshot 2022-10-31 alle 13 00 21](https://user-images.githubusercontent.com/59058746/199003075-801a8274-0a8a-4d02-a24c-823adb6d1a77.png)
Values ​​taken from AMDRadeonX6000Framebuffer.kext

**Comment by perez987** [comment] 2022-12-04 18:35
@Baio1977 
Sorry the delayed answer.
Interesting! It's a clear improvement. I have to try. I'm not at home these days. But when I come back, I'll try and comment.
Thanks.

**Comment by Baio1977** [comment] 2022-12-05 12:34
No problem, I opened this issue to be able to leave traces of any improvements and perhaps verify that some improvements are compatible with all RX 6600XT intended for common PCs.
As for Agdpmod Pikera in my Gigabyte RX every now and then from black screen problems, so I also tested Ignore with which it always starts on the screen, but unfortunately I lose the DP signal and therefore I set this choice aside.

**Comment by perez987** [comment] 2022-12-07 09:38
@Baio1977 
Not tried yet what you comment above.
I see something interesting. Indeed, RX 6600 takes longer from Apple logo and progress bar up to the Desktop than the RX 580. Having the RX 6600 without any specific setting (no code in config.plist, no SSDT, no Henbury patch, no sPPT, only WhateverGreen and agdpmod=pikera) time seems to be shorter, as short as with the RX 580.

**Comment by perez987** [comment] 2022-12-07 19:28
@Baio1977 
Good night. I've tried adding properties from AMDRadeonX6000Framebuffer.kext, same properties as you. But, in my case, scores are not higher.

**Closed as completed** 2022-12-07 19:28 UTC
Labels: documentation
